#!/bin/bash
#
# simBuild
# build a RadioHead example sketch for running as a simulated process
# on Linux.
#
# usage: simBuild sketchname.pde
# The executable will be saved in the current directory

#INPUT=$1
#OUTPUT=$(basename $INPUT ".ino")

INPUT=generic.ino
OUTPUT=generic

PROJECT_DIR=".."
RADIOHEAD="${PROJECT_DIR}/libraries/RadioHead/RadioHead"
BERADIO="${PROJECT_DIR}/libraries/BERadio"
INCLUDE="-I${PROJECT_DIR}/libraries/Terrine -I${PROJECT_DIR}/libraries/BERadio -I$RADIOHEAD -I${PROJECT_DIR}/libraries/RFM69 -I${PROJECT_DIR}/libraries/DHT -I${PROJECT_DIR}/libraries/DallasTemperature -I${PROJECT_DIR}/libraries/EmBencode -I${PROJECT_DIR}/libraries/HX711 -I${PROJECT_DIR}/libraries/LowPower -I${PROJECT_DIR}/libraries/MemoryFree -I${PROJECT_DIR}/libraries/OneWire"

#CPP=g++
#CPP=clang++
#CPP=/opt/local/bin/g++-mp-4.9
#CPP=/opt/local/bin/g++-mp-5
#CPP=/opt/local/bin/gcc-mp-5
CPP=/opt/local/bin/clang++-mp-3.4

# ./sim/compat.h
CPP_FLAGS="-x c++ -lstdc++ -std=gnu++11 -Os -fno-exceptions -ffunction-sections -fdata-sections -pedantic -fpermissive"
CPP_FLAGS_MORE="-Wall -Wextra -Wno-builtin-macro-redefined -fdiagnostics-color"

$CPP -g -I. -I$RADIOHEAD/RHutil $INCLUDE $CPP_FLAGS $CPP_FLAGS_MORE -DHE_ARDUINO=false -D__unix__ \
    $INPUT \
    $RADIOHEAD/RHGenericDriver.cpp $RADIOHEAD/RHMesh.cpp $RADIOHEAD/RHRouter.cpp $RADIOHEAD/RHReliableDatagram.cpp $RADIOHEAD/RHDatagram.cpp $RADIOHEAD/RH_TCP.cpp $RADIOHEAD/RH_Serial.cpp $RADIOHEAD/RHCRC.cpp $RADIOHEAD/RHutil/HardwareSerial.cpp \
    -o ./sim/$OUTPUT

# $RADIOHEAD/tools/simMain.cpp
