# For AVR (Arduino-Makefile)
CXXFLAGS += -DTELEMETRY_DEVICE_GPRSBEE=true

# For ESP8266 (makeEspArduino)
BUILD_EXTRA_FLAGS += -DARDUINO_ARCH_ESP8266=true
BUILD_EXTRA_FLAGS += -DTELEMETRY_DEVICE_ESP8266=true
